//! Clipboard save / set / restore on the general pasteboard.

use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSString};

/// Markers from nspasteboard.org telling clipboard managers to ignore our
/// temporary content.
const TRANSIENT_TYPES: [&str; 2] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// A copy of every item and representation that was on the clipboard.
pub struct SavedClipboard {
    items: Vec<Vec<(Retained<NSString>, Retained<NSData>)>>,
}

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

pub fn change_count() -> isize {
    general().changeCount()
}

pub fn save() -> SavedClipboard {
    let pasteboard = general();
    let mut items = Vec::new();
    if let Some(current) = pasteboard.pasteboardItems() {
        for item in current.iter() {
            let mut representations = Vec::new();
            for ty in item.types().iter() {
                if let Some(data) = item.dataForType(&ty) {
                    representations.push((ty.clone(), data));
                }
            }
            items.push(representations);
        }
    }
    SavedClipboard { items }
}

fn write_items(items: Vec<Retained<NSPasteboardItem>>) -> bool {
    let pasteboard = general();
    pasteboard.clearContents();
    if items.is_empty() {
        return true;
    }
    let writers: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = items
        .into_iter()
        .map(ProtocolObject::from_retained)
        .collect();
    pasteboard.writeObjects(&NSArray::from_retained_slice(&writers))
}

/// Put `text` on the clipboard. `transient` marks it so clipboard history
/// tools skip it. Returns the new change count.
pub fn set_text(text: &str, transient: bool) -> anyhow::Result<isize> {
    let item = NSPasteboardItem::new();
    let ok = item.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    anyhow::ensure!(ok, "could not prepare clipboard item");
    if transient {
        for marker in TRANSIENT_TYPES {
            item.setData_forType(&NSData::new(), &NSString::from_str(marker));
        }
    }
    anyhow::ensure!(write_items(vec![item]), "could not write to the clipboard");
    Ok(change_count())
}

/// Restore saved contents, unless the clipboard changed since `expected_count`
/// (the user copied something new; theirs wins).
pub fn restore(saved: SavedClipboard, expected_count: isize) -> bool {
    if change_count() != expected_count {
        log::info!("Clipboard changed during paste; not restoring");
        return false;
    }
    let items = saved
        .items
        .into_iter()
        .map(|representations| {
            let item = NSPasteboardItem::new();
            for (ty, data) in representations {
                item.setData_forType(&data, &ty);
            }
            item
        })
        .collect();
    write_items(items)
}
